version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - /app/node_modules
  
  backend:
    build:
      context: .
      dockerfile: account-abstraction/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./account-abstraction:/app
      - /app/node_modules